# Generated by Django 4.2.6 on 2023-10-16 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginCliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DadosPessoais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereço', models.CharField(max_length=200)),
                ('telofone', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
