# Generated by Django 4.2.6 on 2023-10-31 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0002_alter_categoria_options_alter_produto_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categoria'},
        ),
    ]
