# Generated by Django 4.2.6 on 2023-10-31 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_dadospessoais_estado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dadospessoais',
            name='tipo_produtor',
        ),
    ]
