# Generated by Django 4.2.4 on 2023-11-20 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_categoria_produto_delete_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/upload/'),
        ),
    ]
