# Generated by Django 4.2.6 on 2023-10-24 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_Produtor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_produtor', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Tipo Produtor',
                'verbose_name_plural': 'Tipo Produtor',
            },
        ),
        migrations.CreateModel(
            name='Produtor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=15)),
                ('endereço', models.CharField(blank=True, max_length=200, null=True)),
                ('bairro', models.CharField(blank=True, max_length=50, null=True)),
                ('cidade', models.CharField(blank=True, max_length=20, null=True)),
                ('estado', models.CharField(blank=True, max_length=20, null=True)),
                ('cep', models.CharField(blank=True, max_length=20, null=True)),
                ('tipo_de_produtor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='LoginUser.tipo_produtor')),
            ],
            options={
                'verbose_name': 'Produtor',
                'verbose_name_plural': 'Produtor',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('produtor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='LoginUser.produtor')),
                ('tipo_de_produtor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='LoginUser.tipo_produtor')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produto',
            },
        ),
    ]
