# Generated by Django 4.2.6 on 2023-10-06 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LoginUser', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='endereço',
            options={'verbose_name': 'Endereço', 'verbose_name_plural': 'Endereço'},
        ),
        migrations.AlterModelOptions(
            name='produtor',
            options={'verbose_name': 'Produtor'},
        ),
        migrations.AlterModelOptions(
            name='tipo_produtor',
            options={'verbose_name': 'Wayne'},
        ),
    ]
