# Generated by Django 4.2.6 on 2023-10-11 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginUser', '0005_alter_produto_options_produto_categoria'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Endereço',
        ),
        migrations.AlterModelOptions(
            name='produtor',
            options={'verbose_name': 'Endereço', 'verbose_name_plural': 'Endereço'},
        ),
        migrations.AddField(
            model_name='produtor',
            name='bairro',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='produtor',
            name='cep',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='produtor',
            name='cidade',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='produtor',
            name='endereço',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='produtor',
            name='estado',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
