# Generated by Django 4.2.6 on 2023-10-11 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LoginUser', '0006_delete_endereço_alter_produtor_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produtor',
            options={'verbose_name': 'Produtor', 'verbose_name_plural': 'Produtor'},
        ),
        migrations.AddField(
            model_name='produtor',
            name='tipo_de_produtor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='LoginUser.tipo_produtor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tipo_produtor',
            name='tipo_produtor',
            field=models.CharField(max_length=100),
        ),
    ]
