# Generated by Django 4.2.6 on 2023-10-11 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LoginUser', '0008_produto_tipo_de_produto_alter_produto_categoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='tipo_de_produto',
            new_name='produtor',
        ),
    ]
